### ISSUE TITLE
Replace trapezium integration with something else

### ISSUE THREAD

**Issue by richfitz** [traitecoevo/plant#111]
Trapezium integration is done in a few places, but we could use something like Simpson's rule (adjusted for non-equidistant points) fairly easily.

Main tricky bit would be dealing with the cohort refinement.  There, we use the comparison of (a -> b) and (a -> m -> b) where m lies between a and b.  If we used a quadratic approximation, we'd need to compare (a -> b -> c) with (a -> m1 -> b -> m2 -> c), where m1 and m2 lie between a and b and b and c respectively.

The advantage of this move would be to struggle less with dealing with the nonlinear contribution of cohorts to LAI and fitness.

**Comment by dfalster** [comment]
Can revisit if this ever becomes an issue
