### ISSUE TITLE
Compare tree2 against tree before merging

### ISSUE THREAD

**Issue by dfalster** [traitecoevo/plant#129]
(putting issue in tree 1 so we have a record of it after merge)

The code below compares max_growth_rate across a variety of trait values using tree1 and tree2.  The advantage of using max_growth rate is that it integrates over functions for growth, survival and fecundity, so tests all of those in the process. Does not test shading algorithm though.

Using tree1, create data for comparison.

```
library(tree)
library(tree.assembly)

values <- list()
p <- ebt_base_parameters()
lma 	  <- seq_log_range(10^c(-4, 2), 50)
values[["lma"]] <- data.frame(x=lma, f = max_growth_rate("lma", lma, p))
rho       <- seq_log_range(c(200, 1000),   50)
values[["rho"]] <- data.frame(x=rho, f = max_growth_rate("rho", rho, p))
s         <- seq_log_range(10^c(-8, 2), 50)
values[["mass_seed"]] <- data.frame(x=s, f = max_growth_rate("s", s,
	p))
hmat      <- seq_log_range(c(1, 100),   50)
values[["hmat"]] <- data.frame(x=hmat, f = max_growth_rate("hmat", hmat, p))

saveRDS(values, "tree1.rds")
```

Restart R, then generate comparable dataset with tree 2 and compare

```
library(tree2)
library(testthat)

p <- ebt_base_parameters()

cmp <- readRDS("tree1.rds")

values <- list()
for(trait in names(cmp)) {
  message(trait)
	xx <- cmp[[trait]][["x"]]
	ff <- cmp[[trait]][["f"]]
	tr <- trait_matrix(xx, trait)
	values[[trait]] <- data.frame(x=xx, f= max_growth_rate(tr, p))
}

for(trait in names(cmp)) {
	expect_that( values[[trait]], equals(cmp[[trait]], tolerance=1e-7))
}
```

**Comment by richfitz** [comment]
There is an archived version of tree 0.1 on branch `tree010`; that package can be installed at the same time as tree though you'll want to prefix almost every call with an explicit namespace as they use a lot of the same names and are not API compatible.
