### ISSUE TITLE
Consider licensing issues when including model descriptions across multiple papers

### ISSUE THREAD

**Issue by dfalster** [traitecoevo/plant#130]
Suggestion to ask Ethan White about this

**Comment by richfitz** [comment]
CC-BY for the SM would seem the best solution, provided the journals are OK with it.

**Comment by richfitz** [comment]
Heather Piwowar would also be a good person to ask as she has written about CC-BY and plagiarism before.

**Comment by dfalster** [comment]
Wrote a blog post on issue [here](danielfalster.com/blog/2015/08/19/SuppMat/)

**Comment by dfalster** [comment]
thankfully, this turnout not to be a problem, because the latest license used by "Methods  in Ecology and Evolution" journal excludes the SuppMaterial from being covered by the exclusive license applied to the main text. Yay!
