### ISSUE TITLE
Complete rename

### ISSUE THREAD

**Issue by richfitz** [traitecoevo/plant#133]
Most functions have moved to being prefixed with `FFW16_`.

- [x] confirm that we're cool with uppercase (it's a bit shouty but then most of the class names are Title Case anyway and it *is* an acronym)
- [ ] Things like `run_ebt()`, which look like the main entry points from `tree.assembly` need to do the Right Thing when given a different model type.
- [ ] `build_schedule()` is also used
- [ ] `equilibrium_seed_rain`
- [ ] `strategy_list`
- [ ] `ebt_base_parameters`

Ideally most of these functions will be generic and work with any underlying plant type.

**Comment by richfitz** [comment]
This really requires an instance of another plant type to test, e.g. #74 and #121

**Comment by richfitz** [comment]
Related to #136

**Comment by richfitz** [comment]
Could do:
```
ebt_base_parameters <- function(model) {
  switch(model,
    FFW16=FFW16_ebt_base_parameters(),
    stop("Unknown model ", model))
}
```
which has the nice property of not breaking any existing code, if a default model of FFW16 is given.

**Comment by dfalster** [comment]
Is this one done now
