### ISSUE TITLE
Document make_FFW16_hyperpar

### ISSUE THREAD

**Issue by richfitz** [traitecoevo/plant#134]

**Comment by dfalster** [comment]
I written a general description of the hyper-parametrisation in `vignettes/physiology.pdf`. Is that what we were looking for, or was it description of R function?

**Comment by richfitz** [comment]
This is in R/ebt_support.R; the parameters are placeholders only:

```r
##' @param B4 Slope of lma / leaf turnover log-log relationship
##' @param lma_0 LMA value...
##' @param k_l_0 ...
##' @param rho_0 ...
##' @param d0_0 ...
##' @param d1 ...
##' @param k_s_0 ...
##' @param B5 ...
##' @param narea_0 ...
```

Don't fill it out yet because I'm renaming everything but once I'm done this needs doing.  Or paste correct things here and I'll fill it in.

**Comment by richfitz** [comment]
Minimal documentation here, linking to a vignette.

Requires #146 so that the crosslink works, and also requires adding this to a vignette.  Possibly its own one with graphs and justifications.
