### ISSUE TITLE
Function to make it easier to generate new plants

### ISSUE THREAD

**Issue by dfalster** [traitecoevo/plant#135]
Porting this over from https://github.com/traitecoevo/tree2/issues/4

Alternative to
```r
p <- ebt_base_parameters()
m <- trait_matrix(0.100003509360981, "lma")
p2 <- expand_parameters(m, p, FALSE)
pl <- Plant(p2$strategies[[1]])
```

**Comment by richfitz** [comment]
I think that fb15462 fixes this; can now say

```r
strategy_default(p)
```

to generate the default strategy (including any hyperparameters), or do

```r
strategy(trait_matrix(x, "lma"), p)
```

to generate a single strategy with lma set.
