### ISSUE TITLE
OdeRunner should support Plant

### ISSUE THREAD

**Issue by richfitz** [traitecoevo/plant#141]
Currently requires PlantPlus but either should be OK.

**Comment by richfitz** [comment]
Looks like the issue here is that `PlantRunner` needs to be templated to support this, but that triggers the double-template issue in RcppR6.  Worth flushing out but not a crazy priority perhaps?

**Comment by richfitz** [comment]
As in #159, drop PlantPlus from everything aside from conversions, and then this goes away.

**Comment by dfalster** [comment]
Closed via #191
