### ISSUE TITLE
Package name

### ISSUE THREAD

**Issue by richfitz** [traitecoevo/plant#143]
Looks like there's a package called tree already:

http://cran.r-project.org/web/packages/tree/index.html

That's only an issue if we push to CRAN, but might cause confusion.

**Comment by dfalster** [comment]
Upper case TREE is free, http://cran.r-project.org/web/packages/TREE/index.html.

What's the rule about case  sensitive package names?

**Comment by dfalster** [comment]
So we need to change names if we want to submit to cran or install via drat, but fine to install via devtools or local source?.

**Comment by richfitz** [comment]
Not allowed (windows and osx are not case sensitive, even though they're case preserving)

**Comment by richfitz** [comment]
(that was how I found out that maker was not allowed as there was an old package called makeR -- http://cran.r-project.org/src/contrib/Archive/makeR/ )

**Comment by richfitz** [comment]
> So we need to change names if we want to submit to cran or install via drat, but fine to install via devtools or local source?.

Yeah, but that rules out being able to provide binaries via drat ever.  I feel pretty strongly that we should fix this.

**Comment by richfitz** [comment]
Fixed in 43aeeb1
