### ISSUE TITLE
Add patch density to run_ebt_collect

### ISSUE THREAD

**Issue by richfitz** [traitecoevo/plant#151]
Or at least make is easy to work out.  Needed for @dfalster for a figure.

**Comment by richfitz** [comment]
See als #138

**Comment by richfitz** [comment]
Looks like in the EBT we get the numbers this way:

```c++
template <typename T>
std::vector<double> EBT<T>::seed_rain_cohort(size_t species_index) const {
  const std::vector<double> times = cohort_schedule.times(species_index);
  const Disturbance& disturbance_regime = patch.disturbance_regime();
  const double scal = parameters.Pi_0 * parameters.seed_rain[species_index];
  std::vector<double> seeds = patch.at(species_index).seeds();
  for (size_t i = 0; i < seeds.size(); ++i) {
    seeds[i] *= disturbance_regime.density(times[i]) * scal;
  }
  return seeds;
}
```

The key bit here being the `disturbance_regime.density(times[i])` - so this is not stored anywhere but computed as needed.

**Comment by richfitz** [comment]
Did you really want this included in the output?  There are a billion possible things we could include and this one can be computed from the output.  On the other hand I can see it's an important one...

**Comment by dfalster** [comment]
I think this one is important, needed to scale any of measures from patch to metapopulation. happy to recalculate, as long as it's easy and we're guaranteed to get same result.

**Comment by richfitz** [comment]
It's easy enough to add, and I agree that it's pretty key.
