### ISSUE TITLE
Make Patch easier to run without metapopulation structure

### ISSUE THREAD

**Issue by richfitz** [traitecoevo/plant#152]
Needs beginning and end times, and is going to _basically_ be the EBT, but with some of the calculations.

Probably resetting the disturbance regime to something that never gets disturbed, plus adding in the final time would be sufficient.

**Comment by richfitz** [comment]
I forget why this one is useful; what is the use case here?

**Comment by dfalster** [comment]
We already do this, only difference is how we weight see production. In Cohort seed survival get's weighted by patch and plant survival to calculate `seeds_survival_weighted_dt`. If we create a version without patch weighting we have a patch without metapopulation. Alternatively, could consider shifting these integrations into R, but then they don't get stepped with the ODE solver, which seems kinds of key.

**Comment by dfalster** [comment]
@aornugent This is sorted on develop now, correct?

**Comment by dfalster** [comment]
Correct.
