### ISSUE TITLE
Resolve role of PlantPlus

### ISSUE THREAD

**Issue by richfitz** [traitecoevo/plant#159]
`PlantPlus` and `Plant` now have the same number of ODE variables so this should be much easier to harmonise:
- [x] template `PlantPlus` on strategy (may or may not work in practice though it will in theory)
- [x] conversion from `Plant` to `PlantPlus`
- [x] Fix #141 (OdeRunner and Plant)
- [x] Fix #89 (convert EBT output to PlantPlus's internals)

**Comment by dfalster** [comment]
As noted in logs of above commit--

We resolved the role of PlantPlus #159

* PlantPlus removed
* PlantInternals -> Internals
* Internals are more flexible (now include auxillary variables of varying length) at a perfomance cost
* Moved more responsibility of details in implementation to strategy from plant
* Allowed for more flexible strategies to be created that dont depend on area_heartwood for example
* Updated strategy scaffolder to reflect new design

API changes:

* plant$fecundity is now: plant$state("fecundity")
* plant$fecundity_dt is now: plant$rate("fecundity")
* plant$height = 5 is now: plant$set_state("height", 5)
* auxillary state can now be accessed in a similar way: plant$aux("area_leaf")
* competition calcualted directly from height: no longer storing leaf area in plant unless optionally via auxillary
* strategies can be created with the argument: collect_all_auxillary=TRUE, this adds extra variables to be recorded which was the primary purpose of the PlantPlus class
