### ISSUE TITLE
EBT support functions need making generic

### ISSUE THREAD

**Issue by richfitz** [traitecoevo/plant#162]
This is currently blocked by https://github.com/richfitz/RcppR6/issues/23

List of functions we need to support:
- [x] `make_cohort_schedule`
- [x] `cohort_schedule_max_time`
- [x] `validate`
- [x] `run_ebt`
- [x] `run_ebt_collect`
- [x] `run_ebt_error`
- [x] `ebt_base_parameters`
- [x] `plant_list`
- [x] `run_stochastic_collect`
- [x] `FFW16_plant_to_plant_plus`
- [x] `lcp_whole_plant`

Also checkout `PlantRunner` --> possibly not templated?

Once the above have been implemented, we can remove restrictions in following files to complete testing across all types. The tests were restricted to "FFW16" type to prevent failures.
- [ ] `test-build-schedule.R`
- [x] `test-ebt.R`
- [x] `test-parameters.R`
- [x] `test-plant-plus.R`
- [x] `test-plant-runner.R`
- [x] `test-plant-utils.R`
- [x] `test-stochastic-patch-runner.R`
- [x] `test-stochastic-patch.R`
- [x] `test-tools.R`

**Comment by dfalster** [comment]
OK, testing has been expanded to apply across all strategy types (as described in #161). A few tests cannot be applied to second strategy type until this issue is addressed. I've listed the functions to be fixed and test files that need modifying -- all required changes are in first few lines.

**Comment by richfitz** [comment]
PlantRunner relates to #141 I think, and templating that might be tricky due to the design of RcppR6.  Most of the rest of these should be fairly straightforward once I fix that RcppR6 issue referenced above.

**Comment by dfalster** [comment]
Plant runner has been extended to apply across all strategies, so it's just test-build-schedule.R that potentially needs extending. Closing this and opening #202 to address remaining issue.
