### ISSUE TITLE
Extract parameter values for hyperpar function?

### ISSUE THREAD

**Issue by dfalster** [traitecoevo/plant#166]
When using plant it can be useful to sometimes extract the values of the parameters used in some analysis (e.g. for making a table of values for a paper). For normal straegy variables this is possible

```
strategy <- default_strategy()
names(strategy)
```

But we then miss values in the `hyperpar` function. I'm thinking of carving out a separate function giving default values for `hyperpar` function. Sound reasonable?

**Comment by richfitz** [comment]
The hyperpar function is not a property of the Strategy, so this won't really work in a reliable way (we could make it part of the Strategy but that will require a bit of replumbing).

What I've been doing is:

```
p <- FFW16_Strategy(strategy_default=default_strategy())
strategy(trait_matrix(0.1, "lma"), p)
```

which creates a strategy and sets the hyperparameters correctly.

**Comment by dfalster** [comment]
As of 2fee7718669d3ca9cffb39c129732d38e2d9a4d8, we have all hyper parameters as named arguments to the hyper-parametrisation function.

Question now is how to extract these values?

Is there a way or querying for default values or arguments to a function?

**Comment by richfitz** [comment]
`args` is your friend:

```
as.list(args(plant::make_FFW16_hyperpar))
```

**Comment by dfalster** [comment]
Cool, and then `lapply(as.list(args(make_FFW16_hyperpar)), eval))` to get as numeric values

**Comment by richfitz** [comment]
I don't think that eval is actually doing anything; those values are
numeric already.
