### ISSUE TITLE
Problem growing plants via `grow_plant_to_size`

### ISSUE THREAD

**Issue by dfalster** [traitecoevo/plant#174]
Hi @richfitz ,
I'm hoping you might be able to take a look at this. I'm using the `grow_plant_to_size` a lot and mostly it's great. However, this error has come up a couple of times now (when running plant with stateline) : 

```
> res <- grow_plant_to_size(pl, sizes, "height", env, 1000, warn = FALSE, filter = TRUE)
Error: Step size became too small
```

I suspect it's arising because some strange parameter values are being fed in. That can't be avoided when running inside stateline (bc it's searching parameter space it's bound to throw out some wilds values) . Here's a MWE:

```

library(plant)  
traits <- trait_matrix(
 c(10.8552329005728,0.0105249489979936,633.641169104633,0.00227017846696535,3.61377429973252,0.66734,1.99575855688525,0.0567301588978768,900.481925352216,0.278101287831634,0.0183902655344452,0.523884989942541,4.34167189261234,4.520285,0.824983001217059,0.0344755338576102,0.245619588820917,0.260495,5031.78411788144,1.06992910086522,1.1368443297711,50,1),
 c("eta","lma","rho","theta","a_l1","a_l2","a_r1","a_b1","r_r","k_b","k_r","omega","B_kl1","B_kl2","B_ks1","narea","B_lf1","B_lf5","B_lf4","B_rs1","B_rb1","hmat","c_r1")
  )

s <- strategy(traits, scm_base_parameters())
pl <- FF16_PlantPlus(s)

env <- fixed_environment(1)
sizes <- seq_range(c(pl$height, 50), 50)
res <- grow_plant_to_size(pl, sizes, "height", env, 1000, warn = FALSE, filter = TRUE)
```

It's failing within the Ode_Runner code:
```
1: grow_plant_to_size(pl, sizes, "height", env, 1000, warn = FALSE, filter = T
2: grow_plant_bracket(plant, sizes, size_name, env, time_max, warn)
3: runner$step()
4: OdeRunner___PlantRunner__step(self)
```

**Comment by richfitz** [comment]
Even shorter code to trigger the problem

```r
library(plant)
traits <- trait_matrix(
 c(10.8552329005728,0.0105249489979936,633.641169104633,0.00227017846696535,3.61377429973252,0.66734,1.99575855688525,0.0567301588978768,900.481925352216,0.278101287831634,0.0183902655344452,0.523884989942541,4.34167189261234,4.520285,0.824983001217059,0.0344755338576102,0.245619588820917,0.260495,5031.78411788144,1.06992910086522,1.1368443297711,50,1),
 c("eta","lma","rho","theta","a_l1","a_l2","a_r1","a_b1","r_r","k_b","k_r","omega","B_kl1","B_kl2","B_ks1","narea","B_lf1","B_lf5","B_lf4","B_rs1","B_rb1","hmat","c_r1")
  )

s <- strategy(traits, scm_base_parameters())
pl <- FF16_PlantPlus(s)
env <- fixed_environment(1)
```


```r
pl$compute_vars_phys(env)
pl$ode_rates 
## [1]  0.000000e+00 7.785851e+307  0.000000e+00  0.000000e+00  0.000000e+00
```

and of course the second value is mortality; so we're seeing instantaneous death.

IMO; everything is behaving reasonably here.  If you try to clamp these numbers you'll probably get other weridnesses going on.  One option would be to clamp d(mortality)/dt to some number that would allow ODE propagation but reasonable rates of death, but that's likely to bite elsewhere.  There are always more magic numbers that can be introduced to deal with more weird cases.

With diversitree, in this sort of situation (controlling MCMC/optimisation interface suggesting values that are stupid) is to make sure that the system can cope reasonably well with failure.  So in this case the plant can't be grown to a reasonable size, whatever the likelihood is at this point should be zero (-Inf log likelihood).  I don't know if stateline can cope with -Inf but if it can things should be pretty easy.

In the meantime I've tweaked the existing behaviour of `grow_plant_to_size` to discard all plants after the integration failure.  I've thrown a quick check to see if it was likely mortality that caused the trouble.

**Comment by dfalster** [comment]
Thanks very much! Your fix seems to work exactly as needed.

Yes, i agree with your suggested approach of handling failure, rather than patching it up in the dim hope of never failing (I've been down that road in old code, it wasn't pretty). Stateline can handle log likelihoods  of -Inf, indeed this is what we already return when the plant fails to grow (at all), even at the smallest size. 

Big question from the above is why was mortality so high, possibly due to low carbon budget (none of the parameters we changed are influencing mortality)!
