### ISSUE TITLE
Document what is needed to install a new strategy

### ISSUE THREAD

**Issue by dfalster** [traitecoevo/plant#183]
@kunstler is currently working to add a new strategy. Once he is done, add a description of how to do this.

**Comment by kunstler** [comment]
Files added for the new strategies:

- R/ff16FvCB.R
- inst/include/plant/ff16FvCB_strategy.h
- src/ff16FvCB_strategy.cpp


add relevant lines with new strategy in 
- inst/RcppR6_classes.yml
- inst/include/plant.h
- src/plant_plus.cpp
- src/plant_tools.cpp

then update 
- R/RcppExports.R 
- R/RcppR6.R
- inst/include/plant/RcppR6_post.hpp
- src/RcppExports.cpp
- src/RcppR6.cpp

**Comment by dfalster** [comment]
Thanks!

Plus run roxygen

**Comment by dfalster** [comment]
To get `lcp_whole_plant` working for the new strategy, also need to create a new wrapper `lcp_whole_plant.PlantPlus<XXX>` function in `plant.R` (e.g. see [here](https://github.com/traitecoevo/plant/blob/ac75a285ca6a2228bc9e1d9e972e65c7558846a0/R/plant.R#L216)). At some point these may be auto-generated (see plant/issues/164). Waiting on RcppR6/issues/23

**Comment by dfalster** [comment]
@johnWilshire We should add this material as a section on the Developer notes page.

**Comment by dfalster** [comment]
See example from Georges Kunstler at https://github.com/kunstler/plantG/ 
This link shows all the changes he has made, not all of which are relevant: 
https://github.com/traitecoevo/plant/compare/master...kunstler:master

Note the changes in Exports files are autogenerated from the yaml files

**Comment by johnWilshire** [comment]
I wrote a small scaffolder that should make adding strategies a lot easier in future.
Detailed instructions can be found in the [developer notes](https://github.com/traitecoevo/plant/blob/scaffolder/inst/docs/developer_notes.md).

I tested it with a strategy named JHW and it seemed to work when I ran `make clean; make all; make install` and installed but I am unsure how to really test it. Any ideas?

**Comment by johnWilshire** [comment]
I do not modify `inst/include/plant/parameters.h` or `inst/include/plant/plant_runner.h` which are modified in the comparison but this might come under #187

**Comment by dfalster** [comment]
Wow, nice one! This is really cool. I checked and it worked as described. i also compared the modifications to @kunstler manual example (from https://github.com/kunstler/plantG/) and the scaffolder appeared to capture everything so far! 

Some thoughts:

- FF16 is a better default than FF16r
- can we change it to use any of the existing strategies as a template? I was looking at the files in `templates` and as far as I could see, we could copy the files from their actual location (e.g. `inst/include/plant/ff16_strategy.h`) and then do a find replace on that?
- probably include  `inst/include/plant/parameters.h` in this change, but as you suggest `inst/include/plant/plant_runner.h` will come under #187
- `R/scm_support.R` --> would be great to automate this too if possible. We can replace the references to `Either \code{"FF16"}, \code{"FF16r"}, or  \code{"ff16FvCB"}.` with something more generic that doesn't need changing. So that just leaves the `hyperpar` and `make_hyperpar` functions to modify.
- I wonder if a function like `list_strategy_types` might be a good addition, returning a list of possible strategies? That might help in generalising `hyperpar` and `make_hyperpar` 

In the developer notes

- `R/reference_plant.R` --> can be ignored as doesn't need changing
- `R/scm_support.R` --> would be great to automate this too if possible
- Need new steps, after 4:
    - Modify the files s`rc/NAME_strategy.cpp` and `inst/include/plant/NAME_strategy.h` to reflect any desired changes in biology
    - Rereun `make`
    - Write suitable tests for your new strategy and run `make test`

**Comment by dfalster** [comment]
In addition, is there any chance we can replace purr::map functions with base R? Important to avoid extra package dependencies where possible.

**Comment by johnWilshire** [comment]
Thanks

* I can update the default strategy template to be FF16 instead of FF16r but: 
* You are right: I think we should just scan and generate templates on the fly from the provided strategy and use FF16 as the default.

* The scaffolder updates `R/smc_support.R` in in 7705142 but it just adds the strategy to map to FF16's hyper parameters but it will be easy to modify this to reflect the actual strategy.

* I will update the documentation to be more generic so then the above works and no documentation has to be changed.

* list_strategy_types already exists but it is in `tests/testthat/helper-plant.R` so we would just have to move it into maybe `R/plant.R` or `R/util.R`  or a new `R/strategy.R`?

I will update developer notes to reflect these comments and tag this issue.

**Comment by dfalster** [comment]
Sounds good
