### ISSUE TITLE
Developer notes

### ISSUE THREAD

**Issue by dfalster** [traitecoevo/plant#189]
Need to add notes about code structure and development and  process, including 

- Gitflow workflow, e.g. see [here](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow), [here](https://git-scm.com/book/en/v2/Git-Branching-Branching-Workflows) or [here](https://blog.axosoft.com/gitflow/)
- Code structure
- Where to find various bits

**Comment by dfalster** [comment]
Add also info about makefile structure, location of cos, how website is built etc

**Comment by johnWilshire** [comment]
I was thinking that I would do this in an Rmarkdown file in `inst/docs` then add it to the files that are copied over to `/vignettes`. This is so it will be built into a pkgdown article and then we can link to this article from the `README.md`, What do you think?

**Comment by dfalster** [comment]
Sounds good.

**Comment by johnWilshire** [comment]
The development notes draft can be found [here](https://github.com/traitecoevo/plant/blob/691fa78f710ff2b97ab1691cbc52822f48a426a7/inst/docs/developer_notes.md).

Comments are appreciated. 

I feel the code structure section needs more specifics and I will try to add to this as I get more comfortable with the codebase outside of `inst/docs`.
I was unsure of what to say in the gitflow section as the link says a lot but I can add more specific instructions if you think it would be helpful.

I also left off some of the makefile targets as I felt they were pretty internal. 

Let me know if you would like more detail in any section.

**Comment by dfalster** [comment]
Great start. 

Re the developer notes and git flow, let's give a brief overview of the workflow. i.e. all development is on the development branch, occasionally we'll make a new release on main. We also use feature branches off the development branch. Issues are here (link), etc.  I think we perhaps should also say something about branches in the main readme, like in the [BayesianTools package](https://github.com/florianhartig/BayesianTools). They also explain how to install different versions which seems like a good idea. Plus we should link to developer notes off the main readme.

**Comment by johnWilshire** [comment]
Sure thing, I have made these changes and tested `make website` in a fork. Here is the [forked site](https://johnwilshire.github.io/plant/), some of the links may be broken (pointing back to the traitevoeco site)

The easiest way to install different versions seems to be through our [github releases](https://github.com/traitecoevo/plant/releases) but the latest release is `v0.0.2` and the main repo is `1.0.0`  should we plan a release for `v1.0.0`?

**Comment by dfalster** [comment]
Looks good, though need to fix the formatting of the "How to install different versions" title

Yep, good idea for the release. Let's keep cleaning up a few things then make a new release. Though perhaps 1.0.0 should be the version i used for the paper in MEE (1.5 years ago) and new release version 1.1.0? thoughts?

**Comment by johnWilshire** [comment]
Good catch on the formatting.

I think that would make sense to have the MEE one as `1.0.0`.

I was going to delete my fork and push to develop and then work on #183 thoughts?

**Comment by dfalster** [comment]
Yes, let's do that. I'll add a tag for MEE version as 1.0.0 and we'll make a new release shortly.

Starting on #183 seems good. That will get you more into the code.

Before doing that, can you find out what controls the content of the "getting started" tab on the website?

**Comment by johnWilshire** [comment]
From [pkgdown navbar](http://pkgdown.r-lib.org/articles/pkgdown.html#navbar2) I think it adds getting  started if you have a vignette with the same name as the package.

**Comment by dfalster** [comment]
Some great advice here. http://r-pkgs.had.co.nz/release.html

Suggest adopting the 1.0.0.9000 forget for version number on development file, and adding a News.md file
