### ISSUE TITLE
runner_plant_internals slowdown

### ISSUE THREAD

**Issue by johnWilshire** [traitecoevo/plant#192]
In 381e08b to resolve #187 I introduced `runner_plant_internals` in `plant.R` to replace `oderunner_plant_size` in `src/plant_tools.cpp`.

I thought it would be a good idea to benchmark it after reading performance section of the README.md in [richfitz/thor](https://github.com/richfitz/thor).

### Results of the quick benchmark against the master branch: 

<img width="695" alt="screen shot 2018-01-29 at 1 28 39 pm" src="https://user-images.githubusercontent.com/1732458/35491544-35b016a6-04fb-11e8-9c4c-c70e9fd5abd2.png">

Converting from the c++ function to the generic R function almost doubled the how long it took to run the vignette in `/inst/docs/src/plant.R`!!! 

An easy solution to this I think would be to go back to c++ and have it like the old `oderunner_plant_size` ie not strategy generic. and have one of these functions per strategy then 
 in R have a selector function like say `get_runner_internals_fun(strategy)` which then uses `strategy$name` to get the required cpp function for use in `grow_plant_to_size` and other functions maybe using `get`.

Not a super elegant solution but it is hard to have a generic function to get the plant internals from an `OdeRunner` as  neither `Lorenz` nor `OdeR` have any plant objects so the compiler doesn't like it at compile time.

**Comment by johnWilshire** [comment]
0a15f96 new benchmark for 0a15f96 down to 2.40 but .2 of a second  seems to have been added.

<img width="310" alt="screen shot 2018-01-29 at 3 13 50 pm" src="https://user-images.githubusercontent.com/1732458/35493400-0a4493b4-0507-11e8-8374-dfb0bcf5e131.png">

**Comment by dfalster** [comment]
Hi @johnWilshire , thanks for checking this out and the proposed solution. I agree with your decision to prefer speed over simplicity. A 10% speed increase is bearable, a 100% is not. So let's go with your updated solution.

**Comment by dfalster** [comment]
benchmark's here confirm the above: the first update about doubled execution time,  the second whereas the second update only added about 10%

```
commit fac6cbc (original)
Rscript inst/docs/src/plant.R  2.26s user 0.15s system 98% cpu 2.461 total
Rscript inst/docs/src/plant.R  2.22s user 0.16s system 98% cpu 2.412 total
Rscript inst/docs/src/plant.R  2.30s user 0.16s system 98% cpu 2.502 total

commit 3d81003 (1st update)
Rscript inst/docs/src/plant.R  4.20s user 0.16s system 99% cpu 4.387 total
Rscript inst/docs/src/plant.R  4.24s user 0.14s system 99% cpu 4.421 total
Rscript inst/docs/src/plant.R  4.38s user 0.15s system 98% cpu 4.573 total

commit f9f882f (2nd update)
Rscript inst/docs/src/plant.R  2.52s user 0.16s system 98% cpu 2.721 total
Rscript inst/docs/src/plant.R  2.50s user 0.16s system 98% cpu 2.699 total
Rscript inst/docs/src/plant.R  2.64s user 0.16s system 98% cpu 2.851 total
```
