### ISSUE TITLE
[Pitch] Add extra ODE(s) for water or soil resources

### ISSUE THREAD

**Issue by dfalster** [traitecoevo/plant#205]
Would like to start adding competition for water and / or nitrogen. But more generally, any depleting resource. 

@johnWilshire and I started to map how this could work. We need to add some extra odes to track the level of different resources (e.g. water, nitrogen) in the soil. Key implementation feature are as follows

* Each resources has a single ode, which tracks it concentration. this is monitored at the patch level
* general dynamics are dx/dt = inputs - outputs
* resources need an initial starting condition after distrubance
* inputs come from external sources
* outputs is rate of use by the community.
* The plants are influenced by the current resources levels. In strategy, we already pass in the environment into `compute_vars_phys` so this connection is very easy to implement (assuming we have the physiology sorted out)
* outputs are then determined by the resource uptake rate of plants, integrated across all cohorts and spp. We'd need to figure out where to put this. If we made each individuals resource extraction rate one of the core odes, then these would naturally propagate up to the patch via the ode solver. Would be handled similarly to fecundity, which is multiplied by individual density (in cohort) and then integrated over all cohorts (in species) and summed over species (in patch).  

Current idea is 

- add details of new resources into the environment class, using the existing internals class to store the details (if already has set, get for odes)
- make environment class be templated over strategy, so that strategies become linked to the specific use of the environment class.

The other option would be to make a single environment class that catches all possible uses by strategy. For now templating seems safer.

**Comment by dfalster** [comment]
Have been thinking what to call the different types of competition and resources. Both light and water are resources, and access and uptake rates may be determined by a combination of state, traits and current environment. the key difference is the timescale over which renewal happens.

light is a resource whose dynamics are very *fast* -- it's constantly arriving and can't be stored up in the patch, because losses happen very quickly

stare and nitrogen(by contrast) are resource whose dynamics are very *slow*  -- they arrive slowly and can accumulate within the soil.

**Comment by dfalster** [comment]
Revisiting this with @rafaqz 

made some necessary progress, step as we see it presently

- [x] abstracting strategies and environments (#225, #213, #224, #216)
- [x] reorganise environment to include states
- [x] extended iterator in patch to allow environment state
- [ ] trial adding a state to environment in new strategy & environment
 
Steps towards the latter

- [x] requires fixing #231 (Move Rcpp templated member functions)
- [x] create named state variables for environment and access functions for these. (Could use existing "internals" class?)
 - [x] Interface for plants, when running compute rates, plants need to 
     - [x] Access environment states 
     - [x] Add the rate of water resource extraction to the resource rate of change to give total rate of change (presumably being stored in environment) (as we iterate across all the species, species, cohorts, patch) 
- [x] ability to set external input rates for resources (at first fixed value, at later date may want a specific rate asa function of time, e.g. to give a smooth temporal signal).

At first, we could implement resource extraction with some fixed rates (e.g. per leaf area), before making photosynthesis also depend on the resource level (i.e. no feedback). This will enable us to make sure the ode stepper and integration is working.

Finally, implement dependency of photosynthesis on resource level.

**Comment by dfalster** [comment]
#238 enables templated environments, i.e. a different environment object to go with each strategy. Moreover, the environments have their own ODE for water and resources. Also included is a placeholder for a new water strategy.

Next steps are to

- [ ] introduce ability to set input rates for the new ode
- [ ] check that it is integrating correctly (e.g. linear increase over time with no uptake by plants and constant additions)
- [ ] check plants can access soil ode, i..e can influence photosynthesis
- [ ] enable plant drawdown
- [ ] enable more complex inputs (e.g. periodic since wave)

also make sure to

- [ ] introduce tests
- [ ] enable access to data

**Comment by aornugent** [comment]
Underway as part of #328
