### ISSUE TITLE
Add environment component classes

### ISSUE THREAD

**Issue by rafaqz** [traitecoevo/plant#212]
Environment would be built from templated components that can be composed to create a specific set of behaviours:

- `RadiationEnvironment`: Components with varying levels of accuracy - single layer, interpolation etc.
- `WaterResources`: extended by eg. `ConstantWater` and `StatefulWater` (where resource is drawn down etc)
- `NutrientResources`: as with water.

These would all be available for calculating assimilation and used or not depending on the `Strategy` class.

**Comment by rafaqz** [comment]
`compute_environment` would be run on each component. The tricky part will be dividing up the state vector between components.

**Comment by dfalster** [comment]
Addressed via #235
