### ISSUE TITLE
Replace references to child object variables like "area_leaf" with generic interface methods

### ISSUE THREAD

**Issue by rafaqz** [traitecoevo/plant#213]
https://github.com/traitecoevo/plant/blob/ee692a705e3c444207c361ee1d6424ee5aca8e98/inst/include/plant/plant.h#L70

plant.h probably shouldn't know about the "area leaf" state variable. We should remove any direct accesses to fields across levels in the hierarchy and replace them with generic getter methods, like `strategy->competition_effect_state`. 

Decoupling the levels in the hierarchy and forcing all access through a generic interface will free things up to add arbitrary strategies.

**Comment by dfalster** [comment]
agreed!

**Comment by rafaqz** [comment]
Great!

Similarly I'm thinking "height" should also not be set directly. Instead `setsize()`/`getsize()` methods should be called and defined  state represents size for a set of variables. So for most objects size is an abstraction of some measure of a plants development that we define lower down. It might equally be biomass/root depth/etc, but only the lower level methods, say in a strategy implementation should "know" that. 

Which also means changing `height` variables everywhere to `size`.

**Comment by dfalster** [comment]
Addressed via #235
