### ISSUE TITLE
Current limits on modularity

### ISSUE THREAD

**Issue by rafaqz** [traitecoevo/plant#219]
I'm working on the modular assimilation components.

The C++ is relatively straightforward to make modular - assimilation can be a templated component of FF_16 strategy, and `assimilation` and `assimilation_leaf` methods belong to it. Then you can just inherit and define variants for assimilation over a distribution, single layer etc. But its hard to cleanly translate this to being controlled by R.

The current method uses booleans like `plant_assimilation_over_distribution` in `Control` to switch methods. This is coupling all optional model components through the `Control` object which will need to hold all control parameters for all model components in future - say booleans like `plant_water_uptake_over_depth`. 
It also locks the implementation to the set of current formulatiions as the calling code has to actually list all the possible branches. Adding an additional assimilation formulation will required a new boolean or enum in control.h and another conditional branch in all of the strategies that use assimilation.

These things are probably fine, they just add a few layers of boilerplate and fall short of the kind of clean modularity I was hoping for. I would usually try to avoid using a runtime branch to choose a formulation by putting all paramters in the modular classes, which are selected with templating at compile time. This means the calling code doesn't have to list all of the options. But I think that will add some RcppR6 boilerplate anyway.

So just putting everything in Control.h is probably the best option. But I wasted a few hours realising that...

I guess it would be interesting to discuss what the tolerable levels of boilerplate are, and ways of translating improvements in modularity to the R calling methods.

**Comment by rafaqz** [comment]
An additional barrier to modularity is the amount of R that needs to be written to wrap a new strategy, even after RcppR6. This will prevent adding modular components to a strategy with templating, as each will need a whole R file for the strategy, at 287 lines for ff16.R.

 We should be able to generalise this a lot more.

**Comment by dfalster** [comment]
Good insights!

R

> An additional barrier to modularity is the amount of R that needs to be written to wrap a new strategy, even after RcppR6. This will prevent adding modular components to a strategy with templating, as each will need a whole R file for the strategy, at 287 lines for ff16.R.
> 
> We should be able to generalise this a lot more.

Just checking whether you've seen the strategy scaffolder? I think this creates some of that extra stuff. See 

- https://github.com/traitecoevo/plant/blob/develop/inst/docs/developer_notes.Rmd#L159
- https://github.com/traitecoevo/plant/blob/develop/inst/scripts/new_strategy_scaffolder.R

**Comment by rafaqz** [comment]
No I hadn't seen that. Ok that does reduce the workload a little.

**Comment by dfalster** [comment]
From memory, the scaffolder builds off an existing strategy. So all of the contents of the new file (equivalent of ff16.r) file and the yaml are auto generated. The only part of ff16.r that is specific to that strategy is the  hyperparameter function.

**Comment by rafaqz** [comment]
I was still hoping for a lot more modularity than that!:) As an example from my other work, these formulations are all totally decoupled from anything else in the package: https://github.com/cesaraustralia/Dispersal.jl/tree/master/src/rules

The main Dispersal.jl file exports their names as a convenience so you don't have to manually import them, but doesn't actually have to for them to work. They are not referenced anywhere else at all. This  means that adding new formulations of your own has zero boilerplate, you just define the struct (ie class) with its parameters and control parameters included, then write the formulation method. Then you can use that as a component a model straight away, as if it's part of the package.

That wont be totally possible in C++/R but we can hopefully get a lot closer to it. Having no overheads to adding new formulations is pretty great.

**Comment by dfalster** [comment]
For now we'll use the existing strategy scaffolder
