### ISSUE TITLE
what to call height?

### ISSUE THREAD

**Issue by rafaqz** [traitecoevo/plant#223]
height is very strategy specific as we have discussed. But `size` is already a common c++ function so it would be confusing in a lot of places.

What about `individual_size` or something?

**Comment by dfalster** [comment]
Hmm, that's a hard one. The apple thesaurus suggests

> dimensions, measurements, proportions, magnitude, largeness, bigness, bulk, immensity, amplitude, hugeness, vastness. 

Nahh.

`individual_size` is good its specific. But long so annoying to type. Does that mean on R side everything previously called `height` will now be `individual_size`?

**Comment by rafaqz** [comment]
Yeah its too long, but I had the same reaction to the thesaurus. Guess that is why size is already used for everything lol... The state name can still be "size", but R will have methods `size` as well so it would be confusing.

`indsize` `getsize` `plantsize` ?

**Comment by dfalster** [comment]
`individual_size` maybe best.

**Comment by aornugent** [comment]
I'd particularly like to be able to change state names as part of a strategy:
```c++
  static std::vector<std::string> state_names() {
    return  std::vector<std::string>({
      "bigness",
      "mortality",
      "fecundity"
      });
  }
```

On the R side they'd be accessed with getters and setters
```
p <- K93_Plant()
p$state("bigness")
```
and we can keep using fixed state indexes the C++ side. Then `SIZE_INDEX` might even be ok (see: https://github.com/traitecoevo/plant/issues/215).
