### ISSUE TITLE
Generalise Environment: canopy_openness -> patch_competition ?

### ISSUE THREAD

**Issue by rafaqz** [traitecoevo/plant#224]
is that the general meaning of this?

**Comment by dfalster** [comment]
yes, but `patch_competition` maybe too general.

where in code are you thinking?

**Comment by rafaqz** [comment]
Mostly patch.h and environment.h

They also use of `*light_environment` methods which would need to be renamed, maybe to `competetive_environment`

**Comment by rafaqz** [comment]
I guess the alternative to this is changing the names in patch and templating Environment, leaving the methods specific to particular environmental drivers

**Comment by dfalster** [comment]
I agree that the methods in `patch.h` should be have a more name. As we discussed, there may be several form of `interaction`, with instantaneous size-based competition for access to a resource (like light) being one of these. It's unclear to me yet how we generalise this to cover a range of cases. Solution to that should probably dictate the renaming

**Comment by rafaqz** [comment]
That's one reason I was suggesting templating `Environment` and defining an abstract parent type as with stategy. Then we can have multiple environments and composites environments.

But dealing with multiple competition variables would mean that `competetive_environment` is not `double` anymore, but a tuple or struct holding multiple competition factors. So some templating would have to be in `Patch` as well to deal with that.

I'm experimenting with implementing it now so I can at least think a bit better about how it could work, but as you would know it's not so straightforward with C++/RcppR6! - the amount of code change required to propagate templated arguments through a few types is pretty shocking tbh, I'm used to it being zero lol.

**Comment by dfalster** [comment]
Let’s try that. 

Thanks for your patience on C++/RcppR6 front!

**Comment by rafaqz** [comment]
It's fairly easy to implement the C++. But I'm struggling with getting something like `Patch` constructing correctly with additional templated variables. Just templating everything and getting it building in C++ and R isn't enough. I'm not sure what the missing step is and the chain of construction is pretty long if you start from R.

**Comment by dfalster** [comment]
@johnWilshire made an attempt at templating on environment. Check out his commit here
https://github.com/traitecoevo/plant/commit/e4e5358fcf2236683d2b7658635717e719e6399d
in particular environment.h Might give some ideas?

**Comment by dfalster** [comment]
Addressed via #235
