### ISSUE TITLE
Patch shouldn't know about light

### ISSUE THREAD

**Issue by rafaqz** [traitecoevo/plant#225]
Environments need to be generalised in Patch.

Currently the patch calls `compute_light_environment` and `rescale_light_environment`.

Can these be generalised to `compute_environment` and `rescale_environment` for all cases?

**Comment by dfalster** [comment]
Yes.

**Comment by dfalster** [comment]
I actually can't quite recall the need for `rescale_light_environment`. I think it's an optimisation deigned to avoiding full recreating the full light environment object. It's used here:
https://github.com/traitecoevo/plant/blob/ee692a705e3c444207c361ee1d6424ee5aca8e98/inst/include/plant/patch.h#L236

And the controlling parameter `environment_light_rescale_usually` is set to false by default:
https://github.com/traitecoevo/plant/blob/ee692a705e3c444207c361ee1d6424ee5aca8e98/src/control.cpp#L24

**Comment by rafaqz** [comment]
Maybe we can push the logic to the environment and just pass in the Boolean. Patch probably shouldn't be aware of the optimisationa

**Comment by rafaqz** [comment]
Q4q4q44f

**Comment by dfalster** [comment]
Addressed via #235
