### ISSUE TITLE
use header-only style?

### ISSUE THREAD

**Issue by rafaqz** [traitecoevo/plant#226]
This would make it a lot easier to read the model definitions, and possibly help function inlining, which would improve performance.

The drawback is a slight increase in compile time.

**Comment by dfalster** [comment]
At least for a models strategy and environment objects, so that science stuff is as compact as possible.

**Comment by dfalster** [comment]
We won't be doing this more for now. In addressing inheritance (#267) @rafaqz discovered that we couldn't use header only and the level of templating and/or inheritance  we're doing.

If anything, I wonder whether we should move some bits away from header only - as this drastically slows compile time.
