### ISSUE TITLE
StochasticPatch should inherit from Patch

### ISSUE THREAD

**Issue by rafaqz** [traitecoevo/plant#227]

**Comment by dfalster** [comment]
There's a fair bit of overlap between Patch and StochasticPatch. StochasticPatch only does a few things differently. @rafaqz was thinking we could streamline the amount of code by inheriting from Patch.

**Comment by rafaqz** [comment]
This is probably not worth the effort, there are a lot of minor differences.

**Comment by rafaqz** [comment]
also dup of #217
