### ISSUE TITLE
move k_I into strategy

### ISSUE THREAD

**Issue by rafaqz** [traitecoevo/plant#229]
currently defined in parameters

**Comment by dfalster** [comment]
Yes. This should be part of the plant’s strategy, as different species may have different values. 

The light env would then be more accuractely interpreted as effective leaf area above.

**Comment by aornugent** [comment]
I'm not fully sure I've understood the order of operations here, but I think the environment constructors need `k_I` to initialise a `Canopy` and do so before a strategy is called. 

`Parameters` uses the `k_I()` function in it's constructor, which appears to be defined in `ff16_environment`, and gets the `k_I` value from `canopy.k_I` which seems a bit circular to me!

**Comment by dfalster** [comment]
One approach is to move k_I into strategy. That would also enable species
to differ in this. I can help with this.

-- 
Daniel Falster

Deputy Director  (Graduate Program) Evolution & Ecology Research Centre & ARC
Future Fellow | School of Biological, Earth & Environmental Sciences |
University
of New South Wales Sydney
P:+61-2-9065 9519 | A: Bdlg E26 Rm 5109 <https://goo.gl/maps/iS3Jc2YmYu62>  |
T: @adaptive_plant <https://twitter.com/adaptive_plant> | W:
http://danielfalster.com
