### ISSUE TITLE
Move Rcpp templated member functions

### ISSUE THREAD

**Issue by rafaqz** [traitecoevo/plant#231]
Move to  to separate file that we update manually

**Comment by dfalster** [comment]
Relates to #228 & richfitz/RcppR6#23

**Comment by dfalster** [comment]
This includes/enables decoupling assimilation from FF16_environment to general environment.

Alternatively could also link an intermediate environment class "light_environment" from which ff16 inherits

**Comment by rafaqz** [comment]
This doesn't seem to be required if the generic fields/methods for Environment are enough for access from R.

**Comment by dfalster** [comment]
Excellent news!

**Comment by dfalster** [comment]
This was towards #235 but appears may not be needed
