### ISSUE TITLE
FF16 coupling and get_from_package

### ISSUE THREAD

**Issue by rafaqz** [traitecoevo/plant#234]
Parameters are still coupled to `FF16_hyperpar`

https://github.com/rafaqz/plant/blob/templated_environment/inst/include/plant/parameters.h#L34

What does this do exactly, and any ideas on how to remove it/push it to R? 

This is the last coupling to ff16 in the generic classes.

**Comment by dfalster** [comment]
Interesting, didn't know about that function. 

the `get_from_package` function is defined [here](https://github.com/traitecoevo/plant/blob/ee692a705e3c444207c361ee1d6424ee5aca8e98/src/util.cpp#L93) and FF16_hyperpar [here](https://github.com/traitecoevo/plant/blob/ee692a705e3c444207c361ee1d6424ee5aca8e98/R/ff16.R#L288)

The reason for this is that the parameters object needs to have all the parameters used in the strategy in its constructor. Moreover, the parameters may be included in the hyperparameterisation function, which is all R based, but not in the cpp code.

One options may be to change the strategy & env objects to have an explicit parameters class each. Then the parameters constructor would only require the template type names (T,E).

Not sure yet if that would work, but it's something we discussed as potentially useful anyway.

**Comment by rafaqz** [comment]
All tests pass with hyperpar as `NULL`. Seems like there are missing tests for this.
