### ISSUE TITLE
Scaffolder still incomplete

### ISSUE THREAD

**Issue by dfalster** [traitecoevo/plant#243]
This commit brought back the FF16r startegy: e6664be873ff95cb5afda46ce01c6efda85e25d1

Note, the scaffolder didn't catch everything needed to introduce a new strategy, so need to review the changes in the above and try with a new strategy.

**Comment by aornugent** [comment]
Some gaps I've identified

- [ ] `tests/testhat/helper-plant.R` fixed environments
- [ ] `R/scm_support.R` hyperpars, make_hyperpars and make_environment,
- [ ] L111 of `R/scm_support.R` seems hardcoded to FF16

**Comment by dfalster** [comment]
More gaps/changes in this commit 83d579d0c812cb37ed57ff93ef0d1b058e71692e

**Comment by dfalster** [comment]
Closed via above commit
