### ISSUE TITLE
tests passing but something isn't right

### ISSUE THREAD

**Issue by dfalster** [traitecoevo/plant#244]
Having allowed multiple environment's with different strategies, all the tests are passing, but something isn't right. 

Here are examples from the vignettes. They kind of work, but really should be behaving identically to the way they were before

```
devtools::load_all()

pl <- FF16_Plant()
pl$state("height")

pl$set_state("height", 10)

env <- fixed_environment("FF16", 1.0)
pl$compute_vars_phys(env)
```

rates are slightly different

```
# Patches of competing plants

p0 <- scm_base_parameters("FF16")
p1 <- expand_parameters(trait_matrix(0.0825, "lma"), p0, FALSE)
p1$seed_rain <- 20
data1 <- run_scm_collect(p1)

matplot(data1$time, data1$species[[1]]["height", , ], lty=1, col=make_transparent("black", 0.25), type="l",
        las=1, xlab="Time (years)", ylab="Height (m)")
```
Kind of similar but should be identical

# Seed rain

Seed rain isn't reducing like it should, suggest competition isn't working properly:

```
p0 <- scm_base_parameters("FF16")
p1 <- expand_parameters(trait_matrix(0.0825, "lma"), p0, FALSE)

for(s in c(0.1, 10, 100, 1000)){
	p1$seed_rain <- s
	out <- run_scm(p1)
	cat(paste(s, " - ", out$seed_rains, "\n"))
}
0.1  -  1.98425257684682
10  -  198.425257684682
100  -  1984.25257684682
1000  -  19842.5257684682
```

**Comment by rafaqz** [comment]
Interesting. I've been working completely to the tests.

Since coveralls is so high it might be some values that are being used in the tests mask the problem, instead of lines not actually being hit.

**Comment by dfalster** [comment]
Indeed. Need to update tests to catch whatever is going on. 

Note the tests with SCM are much slower than normal, indicating that the algorithm is working harder than it should.

**Comment by dfalster** [comment]
NB - @foxeswithdata & @aornugent are both considering the issues here, so please post updates into this issue thread, so that the other can stay informed. I’ll try and look at this again late next week.

**Comment by dfalster** [comment]
We've narrowed down the area where problem was introduced by running this check:

```

devtools::load_all()
p0 <- scm_base_parameters("FF16")
p1 <- expand_parameters(trait_matrix(0.0825, "lma"), p0, FALSE)
p1$seed_rain <- 20
scm <-  FF16_SCM(p1)
scm$run()
scm$seed_rains
```

When working correctly, returns 16.88946.
When working incorrectly, returns 396.8505

Change is between commits daa7c7ddf39518b39408a293e117d1ae5e31c0e4 & f63fd44655656f015cee01300133cb23b6faf6e0

Looking now to see what could have triggered the change: https://github.com/traitecoevo/plant/compare/daa7c7ddf39518b39408a293e117d1ae5e31c0e4...f63fd44655656f015cee01300133cb23b6faf6e0

**Comment by aornugent** [comment]
I've run a few checks between versions:

Mortality is significantly reduced in the new version (density increased to match)
![cohorts](https://user-images.githubusercontent.com/20387761/89010383-d6561980-d351-11ea-9d0a-a1e54d623da4.jpg)

Differences in height look negligble, but amount to large changes during early patch development
![cohort_dff](https://user-images.githubusercontent.com/20387761/89010392-dbb36400-d351-11ea-819a-a1bb4bf37f4a.jpg)

Running individuals at fixed heights in fixed environments gives very similar results, but I'm not sure what the relevant scales for ODE rates are. Results from both versions are plotted here on the log scale, with red indicating where they're not exactly the same:

![fixedenv](https://user-images.githubusercontent.com/20387761/89010503-0bfb0280-d352-11ea-81f6-d839e1a8f63b.jpg)

but summarising the difference between them shows only a marginal difference in mortality:
```
variable        mean_difference       sd
area_heartwood  0.                   0.      
fecundity      -2.64e-12             3.10e-11
height          6.00e-17             2.68e-16
mass_heartwood  0.                   0.      
mortality       3.70e-10             4.47e- 9
```

**Comment by rafaqz** [comment]
This is very interesting. Especially that such small differences lead to such different plots. 

There is a chance this is just straight floating point error extrapolated over the simulation as a lot of things have changed. I routinely get this amount of error converting things from Fortran to Julia that have basically identical math, just different compilers shuffling things in a different order. 

Height at 6.00e-17 is below the machine epsilon for 64 bit float, so actually identical. WIth the other two it really depends how much differences are extrapolated out in the code, to know if it's really an error.

You are also getting less error with parameter values of 1, which is what you expect with one less introduction of floating point error than the other examples.

**Comment by rafaqz** [comment]
@dfalster next week I should be able to go over that commit range and try to track down what is happening.

**Comment by dfalster** [comment]
Thanks @rafaqz, that would be great. There may be several issues entangled, making it hard to diagnose what's going on. Also, while we've narrowed the range in which the change happened, the behaviour of the most current version, on https://github.com/traitecoevo/plant/tree/kohyama-model

**Comment by dfalster** [comment]
Any luck @rafaqz ? @aornugent will be working on this stuff tomorrow so do let us know if you've had a look before then.

**Comment by rafaqz** [comment]
Ok I'm on it. Sorry I have so much on this month.

Can you give me a little detail on how seed rain is mean to work conceptually? like what does `set_seed_rain_index` do?

It would be good it there was a failing test I could write to that made it clear what should be happening.

**Comment by dfalster** [comment]
@aornugent Could you post code to replicate the plots above in https://github.com/traitecoevo/plant/issues/244#issuecomment-666974349? @rafaqz is taking a look at the porblem to see if he can figure out what’s going on.

**Comment by rafaqz** [comment]
I think we just need `virtual` tags on all the inherited methods. 

>Virtual functions are member functions whose behavior can be overridden in derived classes. As opposed to non-virtual functions, the overridden behavior is preserved even if there is no compile-time information about the actual type of the class. If a derived class is handled using pointer or reference to the base class, a call to an overridden virtual function would invoke the behavior defined in the derived class

I'm just used to Julia where everything is `virtual` by default, and forgot to do this once the tests just passed without it.

I'm hoping this is that case anyway!

**Comment by rafaqz** [comment]
The top answer here is a really good explanation:

https://stackoverflow.com/questions/2391679/why-do-we-need-virtual-functions-in-c

**Comment by rafaqz** [comment]
We probably need to rethink the anonymous function callbacks in Patch/Environment - we can't make the templated functions virtual. I mean we should clean it up anyway, it's pretty confusing...

**Comment by dfalster** [comment]
Hi @rafaqz, Ah yes, virtual functions! Honestly, I'd forgotten about that. 

So your first message above suggests this will be an easy fix. The last one suggests perhaps not. Did you try, or are you waiting for me to?

> We probably need to rethink the anonymous function callbacks in Patch/Environment - we can't make the templated functions virtual. I mean we should clean it up anyway, it's pretty confusing..

Can you elaborate?

**Comment by aornugent** [comment]
> @aornugent Could you post code to replicate the plots above in [#244 (comment)]
This is a bit rough and ready: https://gist.github.com/aornugent/6e964a60b0f76ea69b5ccc3e0f36f0fd

Regarding testing in general, is there any value in caching an FF16 run to compare against? The change in relative height differences, for example, would be fairly sensitive to future discrepancies.

**Comment by dfalster** [comment]
Yes we could do that. Easier though would be to add a test for values output of seed-rain, as this integrates the entire model behaviour, including all adaptive routines.

**Comment by dfalster** [comment]
Potential fix added in #249 by @rafaqz - this works for me! Awesome!

@rafaqz Can you explain what was causing the issue was and how the PR fixes it?

**Comment by rafaqz** [comment]
What this is doing is rebuilding the environment object whenever the Parameters object is validated - this happens on parameter construction but also construction of Patch/StochasticPatch. Otherwise it doesn't have the right parameters or integrators.

I still don't understand how it was working before without this, I'll have to track it down in the old code. It also doesn't work just doing it when Parameters is constructed - it has to be in `validate`, which is also called from Patch. That PR probably introduces another bug because patch and parameters will have different environment objects after validation.

So we need more tests to be able to make the changes without breaking something else, and I need to fully understand the chain of object construction to make a sensible design for this, but it's pretty convoluted with the R/C++ interface.

**Comment by dfalster** [comment]
This almost fixed now.
