### ISSUE TITLE
Hyperpars. What to do.

### ISSUE THREAD

**Issue by rafaqz** [traitecoevo/plant#250]
Where will we set the `hyperpar` value on `Parameters` as it no longer happens in the `Parameters` constructor. I don't think this it's tested properly as I'm not breaking it.

Code like this doesn't really make sense now:
https://github.com/traitecoevo/plant/blob/develop/R/scm_support.R#L226

**Comment by dfalster** [comment]
@rafaqz checkout 71f597657009d9f89fc3651e84c57cb454433e58

I think we can remove the hyperpar function from parameters altogether. Sole usage is really in `strategy_list`, so use of hyperpar can be entirely handled on the R side. 

But two issues arising

1. I've left a null pointer in there as I couldn't get it compile with this removed completely. Help!
2. Being able to query the strategy what "type" it is would be really useful. That's what's needed to make https://github.com/traitecoevo/plant/blob/develop/R/scm_support.R#L226 work. Should we add a field string "type" to the parameters, or is there some way we autogenerate this as part of the templating?

**Comment by rafaqz** [comment]
Sounds much better to just use it from R. I'll get it removed completely tomorrow, doing some CESAR things today.\

The type thing should be automated, with some method that returns the hyperpar based on the type. It shouldn't need to be in parameters.

**Comment by dfalster** [comment]
Thanks Raf.

**Comment by rafaqz** [comment]
Cleaned up on my branch. 

Can we just pass the hyperpars method to `strategy_list`? Then its totally arbitrary, just a scripting choice in R.

**Comment by dfalster** [comment]
Yes exactly

**Comment by dfalster** [comment]
This is fixed. hyperpar function is now handled exclusively on the R side.
