### ISSUE TITLE
Inheritance and FF16

### ISSUE THREAD

**Issue by rafaqz** [traitecoevo/plant#251]
Due to limitations in RcppR6 is isn't easy to inherit from concrete classes like `FF16_Strategy`, because they would have to 
be templated as `FF16_Strategy<E>` where E is the environment, also all through the yaml. The solution is to make an FF16_Abstract_Strategy with everything in it that others inherit from, but is never instantiated itself.

This makes things a little clunky in C++, but it's basically how you do everything in Julia because you can't inherit from concrete types. 

At the same time as doing this I would move everything to the header files and get rid of the cpp files so that the templating is easier - otherwise you need to explicitly add it to every single function.

The end result would be: FF16abstract_Strategy.h, with FF16_Strategy.h, FF16r_Strategy.h FF16plus_Strategy.h inheriting from it, with minimal changes.

**Comment by dfalster** [comment]
That's workable!  Would we still need 

- constructors in the derived files?
- to use virtual functions?

could we do the same for the environment files?

**Comment by rafaqz** [comment]
It's turned out to be pretty annoyingly hard in practice, as the base `Strategy` fields aren't visible yet on first compiler pass so you actually have to put everything back in the cpp file. Actually compiling this nested templated inheritance is a nightmare. There are so many technical details to how C++ works to know to write this properly. 

I don't thinks its possible (or maybe just easy) to do this header-only with this kind of nested templated inheritance. It needs a FF16abstract_Strategy.cpp.

This is when Julia just does exactly what you want without even thinking about it - compile is late so it just knows about everything/ or can at least work it out at runtime. I just put a few hours into this when it would take me 5 minutes in Julia, and it doesn't actually work :(

**Comment by dfalster** [comment]
Darn, thanks for trying. Well now we know. So we can drop #226 (header only style)?

Do you think it is possible with the `FF16abstract_Strategy.cpp` ? Let me know if you have tried this. 

What, Julia does better?  Now let me count the ways.....

**Comment by rafaqz** [comment]
I didn't try it with `FF16abstract_Strategy.cpp` that could be possible. The other option is to use header only style without inheritance. It's just annoying that we need to choose one or the other.

**Comment by aornugent** [comment]
Notes from todays discussion on simplifying and composing `plant` environments

- [ ] Suggest refactoring generic environment methods such as ODE states and AdaptiveInterpolator methods into the parent `environment.h`
- [ ] Move the core method of the FF16 (and K93) light environment into a separate "canopy openness module"
- [ ] Strategy specific environments (FF16, K93) can then inherit/be composed of shared modules and set ODE states and rates of environment variables (e.g. available soil water) as needed.

This hopefully means no changes to the Rcpp templating (the R interface still only requires one strategy `T` and one environment `E`) but the flexibility to use multiple environmental variables and methods with minimal boilerplate.

@rafaqz described some potential issues with constructors and inheritance (discussed above) that might get in the way. Please elaborate on anything I've missed or misconstrued.

**Comment by dfalster** [comment]
Ok @rafaqz  - all loose branches have been merged or trimmed!

**Comment by dfalster** [comment]
Closes via #267 #262
