### ISSUE TITLE
Failed to install plant from R 4.0

### ISSUE THREAD

**Issue by eebutler** [traitecoevo/plant#269]
remotes::install_github("traitecoevo/plant", dependencies=TRUE) fails to install under R 4.0 with the following message:
Downloading GitHub repo traitecoevo/plant@HEAD
Skipping 1 packages not available: plant.ml
Installing 5 packages: tinytex, rmarkdown, plant.ml, numDeriv, deSolve
Installing packages into ‘/home/timaeus/R/x86_64-pc-linux-gnu-library/4.0’
(as ‘lib’ is unspecified)
Error: Failed to install 'plant' from GitHub:
  (converted from warning) package ‘plant.ml’ is not available (for R version 4.0.2)

This continues even after issuing the following command: 
Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS="false")

Sys.getenv("R_REMOTES_NO_ERRORS_FROM_WARNINGS")
[1] "false"

I was able to get around this by manually downloading the code (your Option 2 for installation)

**Comment by aornugent** [comment]
Hopefully this works now - please let me know if you have further issues.

**Comment by eebutler** [comment]
This worked great, thank you! But it looks like I installed version 1.2.1
instead of 2.0 - any recommendation to automatically install the latest
version?

**Comment by aornugent** [comment]
This should do it :crossed_fingers: 

```
remotes::install_github("traitecoevo/plant", ref = "v2.0.0", dependencies=TRUE)
```

**Comment by eebutler** [comment]
Thanks! I had tried that based on your Option 3 recommendation for
installation, here's the error:

Downloading GitHub repo ***@***.***
Error in utils::download.file(url, path, method = method, quiet = quiet,  :
  cannot open URL '
https://api.github.com/repos/traitecoevo/plant/tarball/v2.0.0

**Comment by dfalster** [comment]
Sorry Ethan, try without the 'v' in the version number, i.e.:

```
remotes::install_github("traitecoevo/plant", ref = "2.0.0", dependencies=TRUE)
```

**Comment by eebutler** [comment]
All good - that installed without error, but when I check the package
version it is still listed as 1.2.1. It also showed version 1.2.1 during
the building process:

✔  checking for file
‘/tmp/RtmpvAp95q/remotes26c21fa02f19/traitecoevo-plant-afe4718/DESCRIPTION’
─  preparing ‘plant’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Removed empty directory ‘plant/vignettes’
─  building ‘plant_1.2.1.tar.gz’

**Comment by dfalster** [comment]
Sorry @eebutler  - we got a tiny bit tangled with the recent release. We forgot to update the version number, which is why it was showing incorrectly at your end. This has now been changed. 

Also, I've updated the tag to included the `v`, so this should install the latest with correct version number:
```
remotes::install_github("traitecoevo/plant", ref = "v2.0.0", dependencies=TRUE)
```
but equally you can drop the version number and you'll get the latest:
```
remotes::install_github("traitecoevo/plant", dependencies=TRUE)
```

Sorry for the confusion!

**Comment by eebutler** [comment]
No worries! It looks like this did it. I'll be in touch in the near future
with some other research questions we're interested in using plant on.
Thanks for the help!

**Comment by dfalster** [comment]
Great, I look forwards to hearing from you.
