### ISSUE TITLE
K93 runs slower with new strategy/environment inheritance

### ISSUE THREAD

**Issue by aornugent** [traitecoevo/plant#273]
Identified in #262 - FF16 and FF16r appear to be fine, but the additional object complexity seems to cause trouble for K93.

**Comment by dfalster** [comment]
@aornugent  did you mention this got fixed somewhere along the line?

**Comment by aornugent** [comment]
I think this was due to the FF16 using lower Canopy tolerances, leading to faster run times. These weren't being set in K93 but should be after #315.
