### ISSUE TITLE
Canopy Openness Function is Independent of Patch Size

### ISSUE THREAD

**Issue by foxeswithdata** [traitecoevo/plant#277]
The function for calculating canopy openness seems to not have any dependence of patch size, i.e.:

E-a(z) = exp(-k_I * f_compute_competition(height))

When patch size != 1 (for stochastic patches) this should presumably be also dependent on patch size, i.e.:

E-a(z) = exp(-k_I * f_compute_competition(height) / patch_area)

**Comment by dfalster** [comment]
Yes, good catch! Just looking how this can be accommodated.
