### ISSUE TITLE
plant 2.0 release

### ISSUE THREAD

**Issue by aornugent** [traitecoevo/plant#281]
I think it's time to push a new release to master so that new users get all our new bells and whistles when following the "Getting Started" instructions. It's my understanding that the new inheritance stuff breaks old models, meaning we're doing a major version bump. Happy to be wrong though.

Outstanding issues:
- [x] I don't think there's anything major that can't be addressed through minor releases
- [ ] #210 and #270 might be good if we're treating this as a refresh

Outstanding PRs:
- [x] #280 
- [x] #279

**Comment by dfalster** [comment]
> It's my understanding that the new inheritance stuff breaks old models, meaning we're doing a major version bump.
Yes, agreed!
