### ISSUE TITLE
Make most vignettes part of regular build and testing

### ISSUE THREAD

**Issue by dfalster** [traitecoevo/plant#298]
These quickly fall into disrepair if they're not run as part of the regular testing.

The vignettes are currently in another directory as some are slow to build. It's probably only one or two that are slowing things down.

**Comment by dfalster** [comment]
Some good advice here from Ben Bolker: https://github.com/glmmTMB/glmmTMB/issues/364#issuecomment-399696990

We can also make better examples in the roxygen code and run these as tests, all we need is a new test file with:
```
test_examples(path = "../..")
```

However, atm there are few examples included.

**Comment by aornugent** [comment]
Vignettes are now broken following #297 and should be updated as part of this issue.

**Comment by dfalster** [comment]
completed some time ago
