### ISSUE TITLE
Change default parameters to non-mutants

### ISSUE THREAD

**Issue by aornugent** [traitecoevo/plant#337]
In `expand_parameters` we repetitively specify that `mutant = FALSE`. where mutants have no effect on other plants in the community (i.e. have zero density). 

Changing the default setting from `TRUE -> FALSE` will simplify code for common use cases, however code that expects introduced cohorts to be mutants will need updating.

**Comment by dfalster** [comment]
This no no longer an issue with new mutant model, #362, #379
