### ISSUE TITLE
Ideas for optimisation in water use model

### ISSUE THREAD

**Issue by itowers1** [traitecoevo/plant#342]
Just noting some ideas to optimise speed of water use model:

- [x] in ff16w strategy, optimum stem water potential/ci is identified, and the profit is recalculated at this value. Instead, could profit be stored iteratively as optimum position is calculated, and then recalled in FF16w strategy 
     - Update: Solved by storing previous value
- [x] recalling optimum stem water potential/ci between nodes/timesteps breaks due to required transpiration stream exceeding what is theoretically possible using Newton's method of differentiation, but is likely associated with the fact that the last node of a given time step has very different environmental conditions to the first node of the next time step once the forest has matured a little bit. Thus, storing the recalled value between nodes, rather than across calculations, could potentially solve this issue and unlock Newtons method which is proposed to be faster than GSS. 
     - Update: Solved by switching to GSS which is more stable.
- [x] calculation of certain values at a high level without having to input them as arguments. For example, the ratio of maximum profits to maximum costs (lambda in sperry's method) is constant for a given node in a given timestep, meaning that it need only be calculated once for a given call to the leaf model. However, it seems unnecessary to have this as another argument akin to k_l_max in calc_profit, thus I am proposing some other way of having this as a pre-computed variable in ff16w strategy which can be passed to leaf model. 
     - Update: No longer relevant

**Comment by aornugent** [comment]
Awesome - looks like you're really getting to the finer points. We discussed some potential solutions today and I think there's a way to achieve all three and significantly clean up the code. Here's a sketch of some of the core ideas:

### FF16w_Strategy.cpp
```c++
FF16w_Strategy::net_mass_production_dt(...) {
   ...
   
   // update leaf to reflect env. conditions
   leaf.set_physiology(environment);
   
   // track stem hydrology at individual level
   leaf.optimise_psi_stem(vars);

   double assimilation = leaf.profit * area_leaf_; 
   // or
   // double assimilation = leaf.assimilation_per_area * area_leaf_;

   ...
}
```


### FF16w_Strategy.h
```c++
std::vector<std::string> aux_names() {
  std::vector<std::string> ret(
      {"competition_effect", "net_mass_production_dt",  "opt_ci"});
  // add the associated computation to compute_rates and compute there
  if (collect_all_auxiliary) {
    ret.push_back("area_sapwood");
  }
  return ret;
}
```

### leaf_model.h
```c++
class Leaf {
   ...
   void set_physiology(const FF16_Environment &environment);
   void optimise_psi_stem(Internals &vars);
}
```

### leaf_model.cpp
```c++
// set up leaf internal state based on environmental conditions
void Leaf::set_physiology(const FF16_Environment &environment) {
   psi_soil = environment.get_psi_soil() / 1000000;
   PPFD = environment.PPFD;
   k_l_max = K_s * huber_value / (height * eta_c);
   huber_value = ...;
   lamba = ...;
}

void Leaf::optimise_psi_stem(Internals &vars) {
   // start search at prev. node optima
   double psi_stem_initial = vars.aux(aux_index.at("opt_ci"));

   // optimise
   ...
   
   // set new node optima for next timestep
   vars.set_aux(aux_index.at("opt_ci"), psi_stem_next)
}
```

**Comment by a-orn** [comment]
I suppose it wouldn't be much extra code to avoid passing `vars` and setting `opt_ci` as a side-effect...

### FF16w_Strategy.cpp
```c++
FF16w_Strategy::net_mass_production_dt(...) {
   // update leaf to reflect env. conditions
   leaf.set_physiology(environment, height);
   
   // optimise for prohit
   leaf.optimise_psi_stem(vars.aux(aux_index.at("opt_ci")));

   // track stem hydrology as individual auxiliary state
   vars.set_aux(aux_index.at("opt_ci"), leaf.opt_ci)

   double assimilation = leaf.profit * area_leaf_; 
   // or
   // double assimilation = leaf.assimilation_per_area * area_leaf_;
}
```

### leaf_model.cpp
```c++
void Leaf::optimise_psi_stem(double psi_stem_initial) {
   // optimise for profit starting at psi_stem_initial aka. opt_ci at prev. timestep
   y_0 = calc_profit(PPFD, psi_soil, psi_stem_initial, k_l_max)
   
   // set new node optima for next timestep
   leaf.opt_ci = psi_stem_optimised; // might have variable names confused.

   // set profit at optimal psi_stem
   leaf.profit = y_0;
  
  // return nothing because void 
}
```

**Comment by dfalster** [comment]
Thanks for the suggested code Andrew. Yes, I agree with not passing in the vars variable, as this keeps clearer boundary between the different parts. Isaac and I caught up about that and I explained a bit more about vars.

**Comment by dfalster** [comment]
Closed as these have been addressed
