### ISSUE TITLE
`r-actions@master` action is deprecated

### ISSUE THREAD

**Issue by aornugent** [traitecoevo/plant#359]
The [benchmark](https://github.com/traitecoevo/plant/actions/runs/3460001325) and [test coverage](https://github.com/traitecoevo/plant/actions/runs/3460001329) actions are breaking. 

Both have the same message: 
```r
Unable to resolve action `r-lib/actions@master`, unable to find version `master`
```

Checking the `r-lib/actions` repo, `master` no longer seems to be a valid action: https://github.com/r-lib/actions

**Comment by dfalster** [comment]
`master` isn't the action, but the branch on GitHub. Seems that branch has been deleted! We'll need to update the actions. I'll do this on a separate branch then we can pull across to fitness once they're working
