### ISSUE TITLE
TF24: Start new growth model for water

### ISSUE THREAD

**Issue by dfalster** [traitecoevo/plant#387]
@itowers1 has been developing a variant of FF16 with water use, however I think this should be moved to an entirely new strategy. 
It's getting clunky to keep modifying FF16_environment

The new strategy would be based off FF16, but include a variety of changes including 

- [x] Start with FF16 
- [ ] new water model and leaf models (currently implemented as FF16w strategy)
- [ ]  storage of non-structural carbohydrates  (needed to avoid instant increase in mortality when rainfall declines)
- [ ] better root model (FF16 doesn't include course roots (#349)
- [ ] update default pars for allometry (as per Falster et al 2018)
- [ ] integrate over leaf area rather than height (#386)

I propose naming it `TF24`

Thoughts @itowers1 @aornugent ?

**Comment by aornugent** [comment]
Wholeheartedly endorsed! TF24 aligns with the naming convention in
https://traitecoevo.github.io/plant/articles/developer_notes.html#strategies

**Comment by dfalster** [comment]
Have started this via 2adb90f41fd77b278d18b12b93a3e0416f17e3a7 on develop (the scaffolder for creating a new strategy worked perfectly!). Also a new branch `tf24_strategy`. 

@itowers1 will begin 

- porting changes in FF16/FF16W off existing branch into TF24 on `tf24_strategy` branch
- removing FF16W
- simplifying FF16 Environment back to minimal structure (ie remove below ground components)

**Comment by dfalster** [comment]
Initiated via 2adb90f41fd77b278d18b12b93a3e0416f17e3a7

**Comment by dfalster** [comment]
Now managing development via project: https://github.com/orgs/traitecoevo/projects/5/
