### ISSUE TITLE
Move developer docs to wiki

### ISSUE THREAD

**Issue by aornugent** [traitecoevo/plant#431]
**Describe the bug**
I forget to document thinks I learn as a plant developer. Documentation always gets neglected. 

**To Reproduce**
I think @dfalster has tagged a number of documentation issues that need to be finished. 

**Expected behavior**
It's easy to add notes and we grow a deep (ie. low level) knowledge base that remains up to date. 

I think wikis might provide this. Here is a good example: https://github.com/posit-dev/positron/wiki

**Suggested solution**
We move the developer documentation for plant to the wiki.

**Comment by dfalster** [comment]
Thanks! Interesting, I remove the wiki option (we had some old stuff there) and was consolidating about the docs. I agree wiki's could be easier to update, but I really haven't seen good examples. Have you seen any good examples on GitHub? 

After a quick search, I found this page, listing some examples: https://github.com/MyHoneyBadger/awesome-github-wiki?tab=readme-ov-file

There's also the Discussions feature, which could be useful (as an alternative to issues)

https://docs.github.com/en/discussions
